#!/bin/sh

mkdir -p frames
ffmpeg -i "$1" -filter:v fps=30,scale=480:300 -an -shortest temp.mp4
ffmpeg -i "$1" -vn -c:a copy audio.m4a
echo ==============================================================================
echo Running FontVideo Renderer
ffprobe -v error -select_streams v:0 -count_packets -show_entries stream=nb_read_packets -of csv=p=0 temp.mp4
./FontVideo.exe -m -w 80 -h 25 --assets-meta assets/meta_gb2312_16.ini -i temp.mp4 --output-frame-image-sequence frames/f_ -o output.txt --opengl-threads 4
echo ==============================================================================
ffmpeg -framerate 30 -i frames/f_%08d.bmp -i audio.m4a -c:v libx264 -filter:v fps=30 -vf scale=1280:800:flags=neighbor -c:a copy -shortest output.mp4

echo Cleaning up...
rm -f frames/f_*.bmp
rm -f temp.mp4 audio.m4a output.mp4

if [ -f output.mp4 ]; then
	echo Done processing $1
fi
