/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109977-gaca7ef78cc-20230309"
#endif /* AVUTIL_FFVERSION_H */
