/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109961-gad17e29224-20230305"
#endif /* AVUTIL_FFVERSION_H */
